repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:

  - name: vercel-clone
    namespace: front-end
    chart: ./charts/vercel-clone
    installed: false

  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: 5.21.0
    installed: false
